# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5757c71cc0861b9a2a68ed09845fcc0b9476a3afbde7e5e738a46eb0de4121345fdaac799ed803fd9dc4be9423a42d0307c2709e6d600857cc484354c797607a

test:
  secret_key_base: 130179df876a146943fab2e46c6e61b5f2c339738b3851ed1e117787b92feb4ae0c8f6f66aa7a4eeb3bd16269bab6a69635b6e2dd35e951249b83ec8f0a19105


# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
